### ISSUE TITLE
Enhancement: Costs & Previous/Current

### ISSUE THREAD

**Issue by biship** [TechpriestEnginseer/Community-Patch-Events-Development#25]
Love the mod so far. A few quality of life requests:
1. An indication of what civic I am/was on when asked to pick a new civic.
2. Mouse over, or columns showing the impact of each decision. I see a lovely new option, click it and BAM I am at -20 happiness and -400 gpt. I wouldn't have clicked that option if I knew it was going to cripple me for the next 20 turns.

(Oh this is for Civ and Reform v1. The steam web page directed me here)

**Comment by TechpriestEnginseer** [comment]
1. Soon, until I realize how to code UI elements without having it interfere with Vox Populi
2. Hmmm.. what civics were you switching to? It should be obvious what would be the impact of each decision if you were suddenly going from no-upkeep to high-upkeep. But I can't explain the happiness crash, unless you were going from Hereditary Rule to something else, then that's obvious. Otherwise, I'll up the GPT boost[Citizens produce +1 gold per turn along with Merchant earning bonus gold]. (The AIs ironically seems to know which civics will ruin them and which civics will not based on the upkeep than the humans...)

**Comment by biship** [comment]
The extreme happiness hit is my exaggeration, but it probably comes from switching from a civic that creates money, to one that costs a lot of money. The reduction of +gpt to -gpt creates the unhappiness. 

I know it's asking a lot, but it would help if each option showed the impact of picking it. Perhaps at least by showing the gross impact. "Based on your current cities and buildings, this will increase/decrease gpt". Calculating the net impact, after what all bonuses, policies etc do must be more difficult.

**Comment by TechpriestEnginseer** [comment]
brb asking JFD on overriding event text. Although, the -gpt can't create the unhappiness if it's all maintenance? Poverty unhappiness comes from a lower gold income due to the average gold income of other citizens is much higher thany ours.

**Comment by biship** [comment]
Yeah, the -gpt creates unhappiness. I have to switch cities to creating wealth. Each one I switch moves the -gpt closer to 0, and reduces my global unhappiness. Eventually, when I have enough cities creating wealth and I get +gpt, my happiness goes above 0. I Find I have put 3-4 cities on wealth, to get my gpt to 200+, and then my happiness is around 10.  

I really like this mod, I just use it wrong; typically like this:

Civic 1: click, oh that's good, more gpt
Civic 2: click, oh no, -gpt and unhappiness
Civic 3: click, better click something that gives me gpt
Civic 4: click, nice, +gpt
Civic 5: click, lets pick a high cost civic
end result: dam, that last one killed me. -gpt and unhappiness!

**Comment by TechpriestEnginseer** [comment]
Done. Tooltip will gather your current building maintenance and multiply by how much it's costing you. (To make it easier for players, it'll take the "base" maintenance cost and readjust accordingly)
