### ISSUE TITLE
Japan UE: Choice 4

### ISSUE THREAD

**Issue by 8h42** [TechpriestEnginseer/Community-Patch-Events-Development#37]
I can't see the turn duration of WLTKD.
![japan ue](https://cloud.githubusercontent.com/assets/11933188/18411551/760a3c20-77b4-11e6-80c4-40b45441af01.png)

I assume something's wrong with the **EventDuration**.

cf. 
(7) Community Events (v 2)\XML\Hokath\CivilizationEvents.xml

```
<Type>EVENT_JAPAN_UE_CHOICE_4</Type>
<Help>TXT_KEY_EVENT_JAPAN_UE_HELP_CHOICE_4</Help>
<Description>TXT_KEY_EVENT_JAPAN_UE_DESCRIPTION_CHOICE_4</Description>
<IsOneShot>true</IsOneShot>
<EventBuildingClassGlobal>BUILDINGCLASS_JAPAN_UE_DUMMY_2</EventBuildingClassGlobal>
<RequiredAnywhereBuildingClass>BUILDINGCLASS_OPERA_HOUSE</RequiredAnywhereBuildingClass>
<EventDuration>-1</EventDuration>
```

**Comment by TechpriestEnginseer** [comment]
No, that's intentional. Event Duration with Negative are also known as forever, but it doesn't have a <WLTKD> Column. I'll change thanks!

**Comment by Hokath** [comment]
Problem with writing in "5 turns" is that the tooltip doesn't scale with gamespeed, so usually I would set EventDuration to the same time as WLTKDTurns and grab that: since the Duration on its own is documented just as a cooldown control, and it is the additional Expires tag that causes effects to cease. However I am a little uneasy about the UnhappinesNeedsXYZ, because it doesn't have documentation under Expires, but I feel it should be allowed to turn off somehow. See what I'm getting at?

**Comment by TechpriestEnginseer** [comment]
What I would usually do about that would include Lua... but seeing how it's just a simple event choice.. do we really want a reason to?

**Comment by Hokath** [comment]
Naa not worth.

Do you think the UnhappinessNeedMod would stay after the event ended?

**Comment by TechpriestEnginseer** [comment]
Nope, if it has an expire tag that means it'll take out the UnhappinesNeedMod after its duration.

**Comment by Hokath** [comment]
ok I'll do an expires = false tag and make sure it works
