### ISSUE TITLE
Unique Empire events occurring every turn

### ISSUE THREAD

**Issue by jacobgahn** [TechpriestEnginseer/Community-Patch-Events-Development#53]
First started receiving notifications of Washington getting unique empire events in Medieval Era that didn't seem to make sense. Then, Napoleon the same. Now even I get a unique empire event designed for other empires every single turn.

Playing as: Morocco, King, Communitas, standard Vox Pop with EUI and InfoAddict. Community Events v.3

Let me know what else I can do to help. The good game I was on is now unplayable so I'll keep the save around.

**Comment by TechpriestEnginseer** [comment]
That's weird. I can't replicate this. Are you sure you are getting unique empire events designed for others? I'll need a screenshot. Yes, America is weird because it didn't exist in the Medieval Era, but it wasn't fair to deny them events because they started in the Industrial Era. Instead they get similar events that happened during their timeline in the ancient timeline.
- [ ] Investigate more.

**Comment by jacobgahn** [comment]
Definitely getting events from other civs. Bluetooth, Assyria, etc. The first odd thing I noticed in this game was that I completed the event that gave all ranged units trained in the next 10 turns the "sniper" promotion ("Firing Discipline" i think is what actually gets applied). But units created after the 10 turns still got the promotion. Then the unique events started popping probably 40-50 turns after that.

**Comment by TechpriestEnginseer** [comment]
Did you disable Event System?

**Comment by jacobgahn** [comment]
I did try reloading and deselecting events in mod list but the events still occurred.

**Comment by TechpriestEnginseer** [comment]
Why don't you enable logging and tell me what's going on behind the scene. I can't replicate this with any of my testers.

**Comment by TechpriestEnginseer** [comment]
Can't replicate, cannot fix.
